Repository dsccommunity/SqlServerDsc, pull requests merged in 2019-06, with the labels that each got.

#1371 SqlAgentOperator: Fix typo in test
  CHANGELOG.md
  Tests/Unit/MSFT_SqlAgentOperator.Tests.ps1
Labels: needs review

#1372 SqlAgDatabase: Fixes Issue #1358
  CHANGELOG.md
  DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.psm1
  DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.schema.mof
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  README.md
  Tests/Unit/MSFT_SqlAGDatabase.Tests.ps1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: waiting for code fix

#1370 SqlAgentAlert: Adding Resource
  CHANGELOG.md
  DSCResources/MSFT_SqlAgentAlert/MSFT_SqlAgentAlert.psm1
  DSCResources/MSFT_SqlAgentAlert/MSFT_SqlAgentAlert.schema.mof
  DSCResources/MSFT_SqlAgentAlert/en-US/MSFT_SqlAgentAlert.strings.psd1
  Examples/README.md
  Examples/Resources/SqlAgentAlert/1-AddAlert.ps1
  Examples/Resources/SqlAgentAlert/2-RemoveAlert.ps1
  README.md
  Tests/Integration/MSFT_SqlAgentAlert.Integration.Tests.ps1
  Tests/Integration/MSFT_SqlAgentAlert.config.ps1
  Tests/Unit/MSFT_SqlAgentAlert.Tests.ps1
Labels: waiting for code fix

#1369 SqlSetup, SqlWindowsFirewall: Add Upgrade Action for database engine
  Assert-TestEnvironment.ps1
  CHANGELOG.md
  DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.psm1
  DSCResources/MSFT_SqlRS/en-US/MSFT_SqlRS.strings.psd1
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof
  DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1
  DSCResources/MSFT_SqlWindowsFirewall/MSFT_SqlWindowsFirewall.psm1
  DSCResources/MSFT_SqlWindowsFirewall/en-US/MSFT_SqlWindowsFirewall.strings.psd1
  Tests/Unit/MSFT_SqlWindowsFirewall.Tests.ps1
Labels: needs review

#1373 SqlServerDsc: Update CHANGELOG.md
  CHANGELOG.md
Labels: needs review

#1301 SqlSetup: Fix for issue 448
  CHANGELOG.md
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
Labels: ready for merge

#1361 SqlSetup: Added support for RSINSTALLMODE parameter
  CHANGELOG.md
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof
  README.md
  Tests/Unit/MSFT_SqlSetup.Tests.ps1
Labels: ready for merge

#1379 SqlServerDsc.Common: Updates Connect-SQL
  CHANGELOG.md
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review

#1380 Invoke-query updated to allow smo object
  CHANGELOG.md
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review
