Repository dsccommunity/SqlServerDsc, pull requests merged in 2019-07, with the labels that each got.

#1376 SqlServerSecureConnection: Fix issue #1350
  CHANGELOG.md
  DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.psm1
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Tests/Unit/MSFT_SqlServerSecureConnection.Tests.ps1
Labels: waiting for code fix

#1384 Restart-SqlService: Regression test for issues #1306
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: waiting for code fix

#1385 Update CHANGELOG.md
  CHANGELOG.md
Labels: needs review

#1388 Fix minor style violation in SqlSetup - Fixes #1387
  CHANGELOG.md
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
Labels: waiting for author response

#1391 SqlDatabaseUser: New DSC resource
  CHANGELOG.md
  DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.psm1
  DSCResources/MSFT_SqlDatabaseUser/MSFT_SqlDatabaseUser.psm1
  DSCResources/MSFT_SqlDatabaseUser/MSFT_SqlDatabaseUser.schema.mof
  DSCResources/MSFT_SqlDatabaseUser/en-US/MSFT_SqlDatabaseUser.strings.psd1
  Examples/README.md
  Examples/Resources/SqlDatabase/1-CreateDatabase.ps1
  Examples/Resources/SqlDatabase/2-DeleteDatabase.ps1
  Examples/Resources/SqlDatabaseUser/1-AddDatabaseUserWithLogin.ps1
  Examples/Resources/SqlDatabaseUser/2-AddDatabaseUserWithoutLogin.ps1
  Examples/Resources/SqlDatabaseUser/3-AddDatabaseUserMappedToAsymmetricKey.ps1
  Examples/Resources/SqlDatabaseUser/4-AddDatabaseUserMappedToCertificate.ps1
  Examples/Resources/SqlDatabaseUser/5-RemoveDatabaseUser.ps1
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  README.md
  Tests/Integration/MSFT_SqlDatabase.Integration.Tests.ps1
  Tests/Integration/MSFT_SqlDatabase.config.ps1
  Tests/Integration/MSFT_SqlDatabaseUser.Integration.Tests.ps1
  Tests/Integration/MSFT_SqlDatabaseUser.config.ps1
  Tests/Integration/MSFT_SqlServerDatabaseMail.config.ps1
  Tests/Integration/MSFT_SqlServiceAccount.config.ps1
  Tests/Integration/README.md
  Tests/Unit/MSFT_SqlAGListener.Tests.ps1
  Tests/Unit/MSFT_SqlAlias.Tests.ps1
  Tests/Unit/MSFT_SqlDatabase.Tests.ps1
  Tests/Unit/MSFT_SqlDatabaseDefaultLocation.Tests.ps1
  Tests/Unit/MSFT_SqlDatabaseOwner.Tests.ps1
  Tests/Unit/MSFT_SqlDatabasePermission.Tests.ps1
  Tests/Unit/MSFT_SqlDatabaseRecoveryModel.Tests.ps1
  Tests/Unit/MSFT_SqlDatabaseRole.Tests.ps1
  Tests/Unit/MSFT_SqlDatabaseUser.Tests.ps1
  Tests/Unit/MSFT_SqlServerDatabaseMail.Tests.ps1
  Tests/Unit/MSFT_SqlServerEndpoint.Tests.ps1
  Tests/Unit/MSFT_SqlServerEndpointPermission.Tests.ps1
  Tests/Unit/MSFT_SqlServerEndpointState.Tests.ps1
  Tests/Unit/MSFT_SqlServerMaxDop.Tests.ps1
  Tests/Unit/MSFT_SqlServerPermission.Tests.ps1
  Tests/Unit/MSFT_SqlServerRole.Tests.ps1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review

#1400 Connect-SQL: remove domain from win username
  CHANGELOG.md
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review

#1406 SqlServerSecureConnection: Add Parameter SuppressRestart
  CHANGELOG.md
  DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.psm1
  DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.schema.mof
  DSCResources/MSFT_SqlServerSecureConnection/en-US/MSFT_SqlServerSecureConnection.strings.psd1
  README.md
  Tests/Unit/MSFT_SqlServerSecureConnection.Tests.ps1
Labels: needs review

#1407 SqlServerDsc: Changes to Invoke-Query
  CHANGELOG.md
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review

#1409 SqlServerDsc: Consequently use parameters ServerName and InstanceName
  CHANGELOG.md
  DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.psm1
  DSCResources/MSFT_SqlAlwaysOnService/MSFT_SqlAlwaysOnService.psm1
  DSCResources/MSFT_SqlDatabaseDefaultLocation/MSFT_SqlDatabaseDefaultLocation.psm1
  DSCResources/MSFT_SqlRS/MSFT_SqlRS.psm1
  DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1
  DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1
  DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.psm1
  DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1
  DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review

#1410 SqlServerDsc: Changes to helper function Connect-SQL
  CHANGELOG.md
  Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  Tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review
