Repository dsccommunity/SqlServerDsc, pull requests merged in 2020-04, with the labels that each got.

#1485 SqlServerLogin: Set default database
  CHANGELOG.md
  README.md
  source/DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1
  source/DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.schema.mof
  source/DSCResources/MSFT_SqlServerLogin/en-US/MSFT_SqlServerLogin.strings.psd1
  source/Examples/Resources/SqlServerLogin/1-AddLogin.ps1
  tests/Integration/MSFT_SqlServerLogin.Integration.Tests.ps1
  tests/Integration/MSFT_SqlServerLogin.config.ps1
  tests/Unit/MSFT_SqlServerLogin.Tests.ps1
  tests/Unit/Stubs/SMO.cs
Labels: needs review

#1494 SqlAG: Fix hashtables to align with style guideline
  CHANGELOG.md
  source/DSCResources/MSFT_SqlAG/MSFT_SqlAG.psm1
Labels: needs review

#1507 BREAKING CHANGE: SqlDatabaseOwner/Permission/Role: Update parameter Database to DatabaseName
  CHANGELOG.md
  README.md
  source/DSCResources/MSFT_SqlDatabaseOwner/MSFT_SqlDatabaseOwner.psm1
  source/DSCResources/MSFT_SqlDatabaseOwner/MSFT_SqlDatabaseOwner.schema.mof
  source/DSCResources/MSFT_SqlDatabasePermission/MSFT_SqlDatabasePermission.psm1
  source/DSCResources/MSFT_SqlDatabasePermission/MSFT_SqlDatabasePermission.schema.mof
  source/DSCResources/MSFT_SqlDatabaseRole/MSFT_SqlDatabaseRole.psm1
  source/DSCResources/MSFT_SqlDatabaseRole/MSFT_SqlDatabaseRole.schema.mof
  source/Examples/Resources/SqlDatabaseOwner/1-SetDatabaseOwner.ps1
  source/Examples/Resources/SqlDatabasePermission/1-GrantDatabasePermissions.ps1
  source/Examples/Resources/SqlDatabasePermission/2-RevokeDatabasePermissions.ps1
  source/Examples/Resources/SqlDatabasePermission/3-DenyDatabasePermissions.ps1
  source/Examples/Resources/SqlDatabaseRole/1-AddDatabaseRole.ps1
  source/Examples/Resources/SqlDatabaseRole/2-RemoveDatabaseRole.ps1
  source/Examples/Resources/SqlDatabaseRole/3-EnforceDatabaseRoleMembers.ps1
  source/Examples/Resources/SqlDatabaseRole/4-MembersToIncludeInDatabaseRole.ps1
  source/Examples/Resources/SqlDatabaseRole/5-MembersToExcludeFromDatabaseRole.ps1
  source/Examples/Resources/SqlDatabaseRole/6-MembersToIncludeAndExcludeInDatabaseRole.ps1
  tests/Unit/MSFT_SqlDatabaseOwner.Tests.ps1
  tests/Unit/MSFT_SqlDatabasePermission.Tests.ps1
  tests/Unit/MSFT_SqlDatabaseRole.Tests.ps1
Labels: ready for merge

#1493 BREAKING CHANGE: SqlSetup: Refactored to speed up testing
  CHANGELOG.md
  GitVersion.yml
  README.md
  RequiredModules.psd1
  azure-pipelines.yml
  source/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1
  source/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.schema.mof
  source/DSCResources/MSFT_SqlSetup/en-US/MSFT_SqlSetup.strings.psd1
  source/DSCResources/MSFT_SqlSetup/sv-SE/MSFT_SqlSetup.strings.psd1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  tests/Integration/MSFT_SqlSetup.Integration.Tests.ps1
  tests/Unit/MSFT_SqlSetup.Tests.ps1
Labels: breaking change, ready for merge

#1503 BREAKING CHANGE: SqlServerDsc: Make parameter ServerName non-mandatory
  CHANGELOG.md
  README.md
  source/DSCResources/MSFT_SqlAgentAlert/MSFT_SqlAgentAlert.psm1
  source/DSCResources/MSFT_SqlAgentFailsafe/MSFT_SqlAgentFailsafe.psm1
  source/DSCResources/MSFT_SqlAgentOperator/MSFT_SqlAgentOperator.psm1
  source/DSCResources/MSFT_SqlAlias/MSFT_SqlAlias.psm1
  source/DSCResources/MSFT_SqlAlias/MSFT_SqlAlias.schema.mof
  source/DSCResources/MSFT_SqlAlwaysOnService/MSFT_SqlAlwaysOnService.psm1
  source/DSCResources/MSFT_SqlAlwaysOnService/MSFT_SqlAlwaysOnService.schema.mof
  source/DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.psm1
  source/DSCResources/MSFT_SqlDatabase/MSFT_SqlDatabase.schema.mof
  source/DSCResources/MSFT_SqlDatabaseDefaultLocation/MSFT_SqlDatabaseDefaultLocation.psm1
  source/DSCResources/MSFT_SqlDatabaseDefaultLocation/MSFT_SqlDatabaseDefaultLocation.schema.mof
  source/DSCResources/MSFT_SqlDatabasePermission/MSFT_SqlDatabasePermission.psm1
  source/DSCResources/MSFT_SqlDatabasePermission/MSFT_SqlDatabasePermission.schema.mof
  source/DSCResources/MSFT_SqlDatabaseRecoveryModel/MSFT_SqlDatabaseRecoveryModel.psm1
  source/DSCResources/MSFT_SqlDatabaseRecoveryModel/MSFT_SqlDatabaseRecoveryModel.schema.mof
  source/DSCResources/MSFT_SqlDatabaseRole/MSFT_SqlDatabaseRole.psm1
  source/DSCResources/MSFT_SqlDatabaseRole/MSFT_SqlDatabaseRole.schema.mof
  source/DSCResources/MSFT_SqlDatabaseUser/MSFT_SqlDatabaseUser.psm1
  source/DSCResources/MSFT_SqlDatabaseUser/MSFT_SqlDatabaseUser.schema.mof
  source/DSCResources/MSFT_SqlRS/MSFT_SqlRS.schema.mof
  source/DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.psm1
  source/DSCResources/MSFT_SqlServerConfiguration/MSFT_SqlServerConfiguration.schema.mof
  source/DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.psm1
  source/DSCResources/MSFT_SqlServerDatabaseMail/MSFT_SqlServerDatabaseMail.schema.mof
  source/DSCResources/MSFT_SqlServerEndpoint/MSFT_SqlServerEndpoint.psm1
  source/DSCResources/MSFT_SqlServerEndpointPermission/MSFT_SqlServerEndpointPermission.psm1
  source/DSCResources/MSFT_SqlServerEndpointPermission/MSFT_SqlServerEndpointPermission.schema.mof
  source/DSCResources/MSFT_SqlServerEndpointState/MSFT_SqlServerEndpointState.psm1
  source/DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.psm1
  source/DSCResources/MSFT_SqlServerLogin/MSFT_SqlServerLogin.schema.mof
  source/DSCResources/MSFT_SqlServerPermission/MSFT_SqlServerPermission.psm1
  source/DSCResources/MSFT_SqlServerRole/MSFT_SqlServerRole.psm1
  source/DSCResources/MSFT_SqlServerRole/MSFT_SqlServerRole.schema.mof
  source/DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1
  source/DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.schema.mof
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  tests/TestHelpers/CommonTestHelper.psm1
  tests/Unit/MSFT_SqlAlias.Tests.ps1
Labels: ready for merge

#1512 SqlServerDsc: All resources using DscResource.Common
  CHANGELOG.md
  RequiredModules.psd1
  build.yaml
  source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1
  source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1
  source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1
  source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1
  source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1
  source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1
  source/DSCResources/DSC_SqlDatabaseDefaultLocation/DSC_SqlDatabaseDefaultLocation.psm1
  source/DSCResources/DSC_SqlDatabaseOwner/DSC_SqlDatabaseOwner.psm1
  source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1
  source/DSCResources/DSC_SqlDatabaseRecoveryModel/DSC_SqlDatabaseRecoveryModel.psm1
  source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.psm1
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlServerConfiguration/DSC_SqlServerConfiguration.psm1
  source/DSCResources/DSC_SqlServerDatabaseMail/DSC_SqlServerDatabaseMail.psm1
  source/DSCResources/DSC_SqlServerEndpoint/DSC_SqlServerEndpoint.psm1
  source/DSCResources/DSC_SqlServerEndpointPermission/DSC_SqlServerEndpointPermission.psm1
  source/DSCResources/DSC_SqlServerEndpointState/DSC_SqlServerEndpointState.psm1
  source/DSCResources/DSC_SqlServerLogin/DSC_SqlServerLogin.psm1
  source/DSCResources/DSC_SqlServerMaxDop/DSC_SqlServerMaxDop.psm1
  source/DSCResources/DSC_SqlServerMemory/DSC_SqlServerMemory.psm1
  source/DSCResources/DSC_SqlServerNetwork/DSC_SqlServerNetwork.psm1
  source/DSCResources/DSC_SqlServerPermission/DSC_SqlServerPermission.psm1
  source/DSCResources/DSC_SqlServerReplication/DSC_SqlServerReplication.psm1
  source/DSCResources/DSC_SqlServerRole/DSC_SqlServerRole.psm1
  source/DSCResources/DSC_SqlServerSecureConnection/DSC_SqlServerSecureConnection.psm1
  source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1
  source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review
