Repository dsccommunity/SqlServerDsc, pull requests merged in 2020-07, with the labels that each got.

#1576 SqlServerDsc: Documentation updates
  .github/CONTRIBUTING.md
  CHANGELOG.md
  CONTRIBUTING.md
  source/DSCResources/DSC_SqlAGReplica/README.md
  source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.schema.mof
  source/DSCResources/DSC_SqlRSSetup/en-US/DSC_SqlRSSetup.strings.psd1
  source/WikiSource/CredentialOverview.md
  tests/Integration/README.md
Labels: needs review

#1577 SqlServerDsc: Minor changes too schema property descriptions
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  source/DSCResources/DSC_SqlAG/DSC_SqlAG.schema.mof
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.schema.mof
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.schema.mof
  source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.schema.mof
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.schema.mof
  source/DSCResources/DSC_SqlDatabaseDefaultLocation/DSC_SqlDatabaseDefaultLocation.schema.mof
  source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.schema.mof
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.schema.mof
  source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.schema.mof
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.schema.mof
  source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.schema.mof
Labels: needs review

#1581 SqlDatabaseObjectPermission: Update documentation
  CHANGELOG.md
  source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.schema.mof
  source/DSCResources/DSC_SqlDatabaseObjectPermission/README.md
Labels: needs review

#1578 SqlScript, SqlScriptQuery: Add support for disable variables parameter
  CHANGELOG.md
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof
  source/Examples/Resources/SqlScript/4-RunScriptUsingDisabledVariables.ps1
  source/Examples/Resources/SqlScriptQuery/4-RunScriptUsingDisabledVariables.ps1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  tests/Integration/DSC_SqlScript.Integration.Tests.ps1
  tests/Integration/DSC_SqlScript.config.ps1
  tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1
  tests/Integration/DSC_SqlScriptQuery.config.ps1
Labels: waiting for code fix

#1584 SqlServerDsc: Remove italic and inline code-block markdown code
  CHANGELOG.md
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.schema.mof
Labels: needs review

#1585 SqlScript, SqlScriptQuery: Fixes URLs in parameter documentation
  CHANGELOG.md
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof
Labels: needs review

#1587 SqlServerDsc: Updated comment-based help (issue #1500)
  CHANGELOG.md
  azure-pipelines.yml
  source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1
  source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1
  source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1
  source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1
  source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1
  source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1
  source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1
  source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.schema.mof
  source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1
  source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1
  source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/WikiSource/Home.md
Labels: needs review

#1589 SqlSetup: Updated the documentation
  CHANGELOG.md
  source/DSCResources/DSC_SqlSetup/README.md
Labels: needs review

#1590 SqlSetup: Update documentation for Analysis Services
  CHANGELOG.md
  source/DSCResources/DSC_SqlSetup/README.md
Labels: needs review

#1588 SqlServerDsc: Codecov carry forward flag
  CHANGELOG.md
  azure-pipelines.yml
  codecov.yml
Labels: needs review

#1593 CommonTestHelper: Minor style changes
  CHANGELOG.md
  tests/TestHelpers/CommonTestHelper.psm1
Labels: needs review

#1591 SqlSetup: Update requirements section
  CHANGELOG.md
  source/DSCResources/DSC_SqlSetup/README.md
Labels: needs review

#1597 SqlRole: Fix default for ServerName
  CHANGELOG.md
  source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1
Labels: needs review

#1601 SqlDatabaseObjectPermission: Fixes the problem with missing method named 'Where'
  CHANGELOG.md
  source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1
  tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseObjectPermission.config.ps1
Labels: ready for merge
