Repository dsccommunity/SqlServerDsc, pull requests merged in 2020-12, with the labels that each got.

#1640 SqlTraceFlag: New resource
  CHANGELOG.md
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof
  source/DSCResources/DSC_SqlTraceFlag/README.md
  source/DSCResources/DSC_SqlTraceFlag/en-US/DSC_SqlTraceFlag.strings.psd1
  source/Examples/Resources/SqlTraceFlag/1-SetTraceFlags.ps1
  source/Examples/Resources/SqlTraceFlag/2-SetTraceFlagsIncludeExclude.ps1
  source/Examples/Resources/SqlTraceFlag/3-RemoveTraceFlags.ps1
  source/SqlServerDsc.psd1
  tests/Unit/DSC_SqlTraceFlag.Tests.ps1
  tests/Unit/Stubs/SMO.cs
Labels: waiting for code fix

#1644 SqlServerMaxDop Fix for #396
  CHANGELOG.md
  source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1
  tests/Unit/DSC_SqlMaxDop.Tests.ps1
Labels: waiting for code fix

#1646 SqlProtocol: Changes datatype for schema property KeepAlive
  CHANGELOG.md
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.schema.mof
Labels: ready for merge

#1649 SqlDatabaseObjectPermission: Updated unit tests to remove missing `Where()` method error
  CHANGELOG.md
  tests/Unit/DSC_SqlDatabaseObjectPermission.Tests.ps1
Labels: needs review

#1642 SqlAGDatabase Fix for issue #1492
  CHANGELOG.md
  source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1
  source/DSCResources/DSC_SqlAGDatabase/README.md
  tests/Unit/DSC_SqlAGDatabase.Tests.ps1
  tests/Unit/Stubs/SMO.cs
Labels: ready for merge

#1650 SqlServerDsc: Property DscResourcesToExport updates automatically
  CHANGELOG.md
  source/SqlServerDsc.psd1
Labels: ready for merge

#1651 SqlServerDsc.Common\Get-ServerProtocolObject: Updated to throw error/exception if no 'ServerInstances' returned (Fixes #1628)
  CHANGELOG.md
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: ready for merge

#1656 SqlServerDsc: Removes Export-ModuleMember
  CHANGELOG.md
  source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1
  source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1
  source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1
  source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1
  source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.psm1
  source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1
  source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1
  source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.psm1
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1
  source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1
  source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.psm1
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1
  source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1
  source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1
  source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.psm1
  source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1
  source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1
Labels: ready for merge

#1659 SqlServerDsc: Use Get-ComputerName instead of $env:COMPUTERNAME
  CHANGELOG.md
  source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1
  source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.schema.mof
  source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1
  source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.schema.mof
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.schema.mof
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.schema.mof
  source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.psm1
  source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.schema.mof
  source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1
  source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.schema.mof
  source/DSCResources/DSC_SqlDatabaseDefaultLocation/DSC_SqlDatabaseDefaultLocation.psm1
  source/DSCResources/DSC_SqlDatabaseDefaultLocation/DSC_SqlDatabaseDefaultLocation.schema.mof
  source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1
  source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.schema.mof
  source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1
  source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.schema.mof
  source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1
  source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.schema.mof
  source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.psm1
  source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.schema.mof
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.schema.mof
  source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1
  source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.schema.mof
  source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.psm1
  source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.schema.mof
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.schema.mof
  source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1
  source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.schema.mof
  source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1
  source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.schema.mof
  source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1
  source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.schema.mof
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.schema.mof
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.schema.mof
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1
  source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1
  source/DSCResources/DSC_SqlRole/DSC_SqlRole.schema.mof
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof
  source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1
  source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.schema.mof
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.schema.mof
  source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1
  source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.schema.mof
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
Labels: needs review

#1658 SqlProtocol/SqlProtocolTcpIp: Fix verbose messages
  CHANGELOG.md
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1
  source/DSCResources/DSC_SqlProtocol/en-US/DSC_SqlProtocol.strings.psd1
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1
  source/DSCResources/DSC_SqlProtocolTcpIp/en-US/DSC_SqlProtocolTcpIp.strings.psd1
Labels: needs review
