Repository dsccommunity/SqlServerDsc, pull requests merged in 2021-01, with the labels that each got.

#1662 SqlDatabaseMail: Do not enforce parameters not part of configuration
  CHANGELOG.md
  source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1
Labels: needs review

#1665 SqlRSSetup: Fix EditionUpgrade set to $false
  CHANGELOG.md
  source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1
  tests/Unit/DSC_SqlRSSetup.Tests.ps1
Labels: needs review

#1666 SqlAgDatabase: Typo in resource for fix for #1492
  CHANGELOG.md
  source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1
  tests/Unit/DSC_SqlAGDatabase.Tests.ps1
  tests/Unit/Stubs/SMO.cs
Labels: waiting for code fix

#1652 SqlLogin: Added and amended integration tests for logins of 'SqlLogin' type (Fixes #361, #792, #1032, #1050, #1634)
  CHANGELOG.md
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.psm1
  source/DSCResources/DSC_SqlLogin/DSC_SqlLogin.schema.mof
  source/DSCResources/DSC_SqlLogin/README.md
  source/DSCResources/DSC_SqlLogin/en-US/DSC_SqlLogin.strings.psd1
  tests/Integration/DSC_SqlLogin.Integration.Tests.ps1
  tests/Integration/DSC_SqlLogin.config.ps1
  tests/Integration/README.md
  tests/TestHelpers/CommonTestHelper.psm1
  tests/Unit/DSC_SqlLogin.Tests.ps1
Labels: ready for merge

#1675 SqlServerDsc: Fix gitversion in pipeline
  CHANGELOG.md
  GitVersion.yml
Labels: needs review

#1673 SqlRSSetup: Fix SuppressRestart to not be added when $false
  CHANGELOG.md
  source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1
  tests/Unit/DSC_SqlRSSetup.Tests.ps1
Labels: needs review

#1667 SqlServerDsc: Switch to GitHub Action Stale
  .github/stale.yml
  .github/workflows/stale.yml
  CHANGELOG.md
Labels: needs review

#1676 SqlServerDsc: Added SQL Server 2019 Integration Tests (and unit test) plus additional, 'SqlSetup' resource `InstallSharedDir` fix.
  CHANGELOG.md
  CONTRIBUTING.md
  azure-pipelines.yml
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  tests/Integration/DSC_SqlAgentAlert.Integration.Tests.ps1
  tests/Integration/DSC_SqlAgentFailsafe.Integration.Tests.ps1
  tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabase.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabasePermission.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseUser.Integration.Tests.ps1
  tests/Integration/DSC_SqlEndpoint.Integration.Tests.ps1
  tests/Integration/DSC_SqlLogin.Integration.Tests.ps1
  tests/Integration/DSC_SqlProtocol.Integration.Tests.ps1
  tests/Integration/DSC_SqlProtocolTcpIp.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS.config.ps1
  tests/Integration/DSC_SqlRSSetup.Integration.Tests.ps1
  tests/Integration/DSC_SqlRSSetup.config.ps1
  tests/Integration/DSC_SqlReplication.Integration.Tests.ps1
  tests/Integration/DSC_SqlRole.Integration.Tests.ps1
  tests/Integration/DSC_SqlScript.Integration.Tests.ps1
  tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1
  tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1
  tests/Integration/DSC_SqlServiceAccount.Integration.Tests.ps1
  tests/Integration/DSC_SqlSetup.Integration.Tests.ps1
  tests/Integration/DSC_SqlSetup.config.ps1
  tests/Integration/README.md
  tests/Unit/DSC_SqlRS.Tests.ps1
  tests/Unit/DSC_SqlSetup.Tests.ps1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: ready for merge

#1684 SqlServerDsc: Add Script Analyzer rule to help detect if resource do not load SMO
  .vscode/analyzersettings.psd1
  CHANGELOG.md
  azure-pipelines.yml
  source/DSCResources/DSC_SqlAG/DSC_SqlAG.psm1
  source/DSCResources/DSC_SqlAGListener/DSC_SqlAGListener.psm1
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1
  source/DSCResources/DSC_SqlAgentAlert/DSC_SqlAgentAlert.psm1
  source/DSCResources/DSC_SqlAgentFailsafe/DSC_SqlAgentFailsafe.psm1
  source/DSCResources/DSC_SqlAgentOperator/DSC_SqlAgentOperator.psm1
  source/DSCResources/DSC_SqlAlias/DSC_SqlAlias.psm1
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1
  source/DSCResources/DSC_SqlConfiguration/DSC_SqlConfiguration.psm1
  source/DSCResources/DSC_SqlDatabase/DSC_SqlDatabase.psm1
  source/DSCResources/DSC_SqlDatabaseDefaultLocation/DSC_SqlDatabaseDefaultLocation.psm1
  source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1
  source/DSCResources/DSC_SqlDatabaseObjectPermission/DSC_SqlDatabaseObjectPermission.psm1
  source/DSCResources/DSC_SqlDatabasePermission/DSC_SqlDatabasePermission.psm1
  source/DSCResources/DSC_SqlDatabaseRole/DSC_SqlDatabaseRole.psm1
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1
  source/DSCResources/DSC_SqlEndpoint/DSC_SqlEndpoint.psm1
  source/DSCResources/DSC_SqlEndpointPermission/DSC_SqlEndpointPermission.psm1
  source/DSCResources/DSC_SqlMaxDop/DSC_SqlMaxDop.psm1
  source/DSCResources/DSC_SqlMemory/DSC_SqlMemory.psm1
  source/DSCResources/DSC_SqlPermission/DSC_SqlPermission.psm1
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  source/DSCResources/DSC_SqlRSSetup/DSC_SqlRSSetup.psm1
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1
  source/DSCResources/DSC_SqlRole/DSC_SqlRole.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.psm1
  source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1
  source/DSCResources/DSC_SqlWaitForAG/DSC_SqlWaitForAG.psm1
  source/DSCResources/DSC_SqlWindowsFirewall/DSC_SqlWindowsFirewall.psm1
  source/DSCResources/MSFT_SqlDatabaseOwner/MSFT_SqlDatabaseOwner.psm1
  source/DSCResources/MSFT_SqlDatabaseRecoveryModel/MSFT_SqlDatabaseRecoveryModel.psm1
  source/DSCResources/MSFT_SqlServerEndpointState/MSFT_SqlServerEndpointState.psm1
  source/DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1
  source/Examples/Resources/SqlEndpoint/3-CreateServiceBrokerEndpointWithDefaultValues.ps1
  source/Examples/Resources/SqlEndpointPermission/3-AddConnectPermissionToTwoReplicasEachWithDifferentServiceAccount.ps1
  source/Examples/Resources/SqlEndpointPermission/4-RemoveConnectPermissionForTwoReplicasEachWithDifferentServiceAccount.ps1
  source/Examples/Resources/SqlScript/3-RunScriptCompleteExample.ps1
  tests/QA/AnalyzerRules/SqlServerDsc.AnalyzerRules.psm1
  tests/QA/ScriptAnalyzer.Tests.ps1
  tests/Unit/SqlServerDsc.AnalyzerRules.Tests.ps1
Labels: needs review
