Repository dsccommunity/SqlServerDsc, pull requests merged in 2021-02, with the labels that each got.

#1681 SqlDatabaseUser: Pass parameter ServerName to Assert-SqlLogin
  CHANGELOG.md
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1
  tests/Unit/DSC_SqlDatabaseUser.Tests.ps1
Labels: waiting for code fix

#1686 SqlServerDsc: Removes a left-over comment
  .vscode/analyzersettings.psd1
  CHANGELOG.md
Labels: needs review

#1689 SqlTraceFlag: Fix for #1688
  CHANGELOG.md
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1
  tests/Unit/DSC_SqlTraceFlag.Tests.ps1
Labels: ready for merge

#1692 SqlSetup: Connect-SQLAnalysis no longer using LoadWithPartialName()
  CHANGELOG.md
  RequiredModules.psd1
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/DSCResources/DSC_SqlSetup/README.md
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  tests/Integration/DSC_SqlSetup.Integration.Tests.ps1
  tests/Integration/DSC_SqlSetup.config.ps1
  tests/Integration/README.md
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review
