Repository dsccommunity/SqlServerDsc, pull requests merged in 2023-01, with the labels that each got.

#1827 SqlServerDsc: Add GitHub App; Pull Request Quantifier
  .github/prquantifier.yaml
  CHANGELOG.md
Labels: needs review, Extra Small

#1828 `Assert-SetupActionProperties`: Use commands from DscResource.Common
  .vscode/settings.json
  CHANGELOG.md
  source/Private/Assert-RequiredCommandParameter.ps1
  source/Private/Assert-SetupActionProperties.ps1
  source/Private/Test-ServiceAccountRequirePassword.ps1
  source/en-US/SqlServerDsc.strings.psd1
  tests/Unit/Private/Assert-RequiredCommandParameter.Tests.ps1
  tests/Unit/Private/Assert-SetupActionProperties.Tests.ps1
  tests/Unit/Private/Test-ServiceAccountRequirePassword.Tests.ps1
Labels: needs review, Large

#1829 SqlServerDsc: Update quantifier label names and colors
  .github/prquantifier.yaml
  CHANGELOG.md
Labels: Extra Small

#1826 SqlServerDsc: Use `ResourceBase` from DscResource.Base
  .vscode/analyzersettings.psd1
  CHANGELOG.md
  RequiredModules.psd1
  build.yaml
  source/Classes/002.Reason.ps1
  source/Classes/010.ResourceBase.ps1
  source/Classes/011.SqlResourceBase.ps1
  source/Classes/020.SqlAudit.ps1
  source/Classes/020.SqlDatabasePermission.ps1
  source/Classes/020.SqlPermission.ps1
  source/Enum/1.Ensure.ps1
  source/Private/ConvertFrom-CompareResult.ps1
  source/Private/ConvertTo-Reason.ps1
  source/Private/Get-ClassName.ps1
  source/Private/Get-DscProperty.ps1
  source/Private/Get-LocalizedDataRecursive.ps1
  source/Private/Test-ResourceDscPropertyIsAssigned.ps1
  source/Private/Test-ResourceHasDscProperty.ps1
  source/en-US/ResourceBase.strings.psd1
  source/prefix.ps1
  tests/QA/ScriptAnalyzer.Tests.ps1
  tests/Unit/Classes/Reason.Tests.ps1
  tests/Unit/Classes/ResourceBase.Tests.ps1
  tests/Unit/Private/ConvertFrom-CompareResult.Tests.ps1
  tests/Unit/Private/ConvertTo-Reason.Tests.ps1
  tests/Unit/Private/Get-ClassName.Tests.ps1
  tests/Unit/Private/Get-DscProperty.Tests.ps1
  tests/Unit/Private/Get-LocalizedDataRecursive.Tests.ps1
  tests/Unit/Private/Test-ResourceDscPropertyIsAssigned.Tests.ps1
  tests/Unit/Private/Test-ResourceHasDscProperty.Tests.ps1
Labels: needs review, PR extra large

#1830 SqlServerDsc: Add QA tests for commands
  .github/prquantifier.yaml
  CHANGELOG.md
  source/Private/Assert-SetupActionProperties.ps1
  source/Private/Invoke-SetupAction.ps1
  source/Public/Add-SqlDscNode.ps1
  source/Public/Complete-SqlDscFailoverCluster.ps1
  source/Public/Complete-SqlDscImage.ps1
  source/Public/Connect-SqlDscDatabaseEngine.ps1
  source/Public/ConvertFrom-SqlDscDatabasePermission.ps1
  source/Public/ConvertFrom-SqlDscServerPermission.ps1
  source/Public/ConvertTo-SqlDscDatabasePermission.ps1
  source/Public/ConvertTo-SqlDscServerPermission.ps1
  source/Public/Disable-SqlDscAudit.ps1
  source/Public/Enable-SqlDscAudit.ps1
  source/Public/Get-SqlDscAudit.ps1
  source/Public/Get-SqlDscDatabasePermission.ps1
  source/Public/Get-SqlDscServerPermission.ps1
  source/Public/Initialize-SqlDscRebuildDatabase.ps1
  source/Public/Install-SqlDscServer.ps1
  source/Public/Invoke-SqlDscQuery.ps1
  source/Public/New-SqlDscAudit.ps1
  source/Public/Remove-SqlDscAudit.ps1
  source/Public/Remove-SqlDscNode.ps1
  source/Public/Repair-SqlDscServer.ps1
  source/Public/Set-SqlDscAudit.ps1
  source/Public/Set-SqlDscDatabasePermission.ps1
  source/Public/Set-SqlDscServerPermission.ps1
  source/Public/Test-SqlDscIsDatabasePrincipal.ps1
  source/Public/Test-SqlDscIsLogin.ps1
  source/Public/Uninstall-SqlDscServer.ps1
  tests/QA/ScriptAnalyzer.Tests.ps1
  tests/QA/module.tests.ps1
Labels: waiting for code fix, PR extra large

#1808 SqlServerDsc: Resources work with SqlServer v22.0.49-preview
  CHANGELOG.md
  CONTRIBUTING.md
  RequiredModules.psd1
  appveyor.yml
  source/DSCResources/DSC_SqlProtocol/README.md
  source/DSCResources/DSC_SqlProtocolTcpIp/README.md
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.schema.mof
  source/DSCResources/DSC_SqlRS/README.md
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1
  source/DSCResources/DSC_SqlReplication/README.md
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.schema.mof
  source/DSCResources/DSC_SqlScript/README.md
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.schema.mof
  source/DSCResources/DSC_SqlScriptQuery/README.md
  source/DSCResources/DSC_SqlServiceAccount/README.md
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  tests/Integration/DSC_SqlDatabaseObjectPermission.config.ps1
  tests/Integration/DSC_SqlDatabaseUser.config.ps1
  tests/Integration/DSC_SqlProtocol.Integration.Tests.ps1
  tests/Integration/DSC_SqlProtocolTcpIp.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS.config.ps1
  tests/Integration/DSC_SqlReplication.Integration.Tests.ps1
  tests/Integration/DSC_SqlScript.config.ps1
  tests/Integration/DSC_SqlScriptQuery.config.ps1
  tests/Integration/DSC_SqlServiceAccount.Integration.Tests.ps1
  tests/Integration/DSC_SqlSetup.config.ps1
  tests/Integration/README.md
  tests/Unit/DSC_SqlRS.Tests.ps1
  tests/Unit/DSC_SqlReplication.Tests.ps1
  tests/Unit/DSC_SqlScript.Tests.ps1
  tests/Unit/DSC_SqlScriptQuery.Tests.ps1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
  tests/Unit/Stubs/README.md
  tests/Unit/Stubs/SQLServerStub.psm1
  tests/Unit/Stubs/SqlServerStub.psm1
Labels: ready for merge, PR extra large

#1840 SqlAGReplica: Run Update-AvailabilityGroupReplica Once for All AvailabilityReplica Changes
  CHANGELOG.md
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1
  tests/TestHelpers/CommonTestHelper.psm1
  tests/Unit/DSC_SqlAGReplica.Tests.ps1
Labels: ready for merge, PR medium

#1841 `Connect-SQL`: Returns clear error message when status is not Online
  CHANGELOG.md
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
Labels: needs review, PR extra small
