Repository dsccommunity/SqlServerDsc, pull requests merged in 2023-03, with the labels that each got.

#1862 SqlServerDsc: Replace `Import-SQLPSModule`
  CHANGELOG.md
  source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1
  source/DSCResources/DSC_SqlAGReplica/DSC_SqlAGReplica.psm1
  source/DSCResources/DSC_SqlAlwaysOnService/DSC_SqlAlwaysOnService.psm1
  source/DSCResources/DSC_SqlProtocol/DSC_SqlProtocol.psm1
  source/DSCResources/DSC_SqlProtocolTcpIp/DSC_SqlProtocolTcpIp.psm1
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  source/DSCResources/DSC_SqlReplication/DSC_SqlReplication.psm1
  source/DSCResources/DSC_SqlScript/DSC_SqlScript.psm1
  source/DSCResources/DSC_SqlScriptQuery/DSC_SqlScriptQuery.psm1
  source/DSCResources/DSC_SqlServiceAccount/DSC_SqlServiceAccount.psm1
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/DSCResources/DSC_SqlTraceFlag/DSC_SqlTraceFlag.psm1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  tests/QA/AnalyzerRules/SqlServerDsc.AnalyzerRules.psm1
  tests/Unit/DSC_SqlAGDatabase.Tests.ps1
  tests/Unit/DSC_SqlAGReplica.Tests.ps1
  tests/Unit/DSC_SqlAlwaysOnService.Tests.ps1
  tests/Unit/DSC_SqlProtocol.Tests.ps1
  tests/Unit/DSC_SqlProtocolTcpIp.Tests.ps1
  tests/Unit/DSC_SqlRS.Tests.ps1
  tests/Unit/DSC_SqlReplication.Tests.ps1
  tests/Unit/DSC_SqlServiceAccount.Tests.ps1
  tests/Unit/DSC_SqlSetup.Tests.ps1
  tests/Unit/DSC_SqlTraceFlag.Tests.ps1
  tests/Unit/SqlServerDsc.AnalyzerRules.Tests.ps1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: waiting for code fix

#1863 `Install-SqlDscServer`: Fix `ASSysAdminAccounts` and `SqlSysAdminAccounts`
  CHANGELOG.md
  source/Private/Assert-SetupActionProperties.ps1
  source/Private/Invoke-SetupAction.ps1
  source/Public/Install-SqlDscServer.ps1
  tests/Unit/Private/Assert-SetupActionProperties.Tests.ps1
  tests/Unit/Private/Invoke-SetupAction.Tests.ps1
  tests/Unit/Public/Install-SqlDscServer.Tests.ps1
Labels: needs review

#1865 SqlServerDsc: Fix GitVersion configuration
  CHANGELOG.md
  GitVersion.yml
Labels: needs review

#1866 SqlServerDsc: Add workflow that run PSScriptAnalyzer
  .github/workflows/code-analysis.yml
  .vscode/analyzersettings.psd1
  CHANGELOG.md
  RequiredModules.psd1
  tests/QA/ScriptAnalyzer.Tests.ps1
Labels: needs review

#1850 `Get-SqlDscAudit`: `Name` no longer mandatory
  CHANGELOG.md
  source/Classes/020.SqlAudit.ps1
  source/Public/Disable-SqlDscAudit.ps1
  source/Public/Enable-SqlDscAudit.ps1
  source/Public/Get-SqlDscAudit.ps1
  source/Public/New-SqlDscAudit.ps1
  source/Public/Remove-SqlDscAudit.ps1
  source/Public/Set-SqlDscAudit.ps1
  tests/Unit/Public/Get-SqlDscAudit.Tests.ps1
Labels: needs review

#1874 SqlRs: Clearer test naming
  CHANGELOG.md
  tests/Unit/DSC_SqlRS.Tests.ps1
Labels: ready for merge

#1870 SqlRs: Adding checks for ReportServerReservedUrl and ReportsReservedUrl
  CHANGELOG.md
  source/DSCResources/DSC_SqlRS/DSC_SqlRS.psm1
  tests/Unit/DSC_SqlRS.Tests.ps1
Labels: ready for merge

#1875 SqlServerDsc: Fix pipeline script
  CHANGELOG.md
  Resolve-Dependency.ps1
Labels: needs review

#1864 SqlServerDsc: Update initializing header integration test
  CHANGELOG.md
  tests/Integration/DSC_SqlAgentAlert.Integration.Tests.ps1
  tests/Integration/DSC_SqlAgentFailsafe.Integration.Tests.ps1
  tests/Integration/DSC_SqlAgentOperator.Integration.Tests.ps1
  tests/Integration/DSC_SqlAlwaysOnService.Integration.Tests.ps1
  tests/Integration/DSC_SqlAudit.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabase.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseDefaultLocation.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseObjectPermission.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabasePermission.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseUser.Integration.Tests.ps1
  tests/Integration/DSC_SqlEndpoint.Integration.Tests.ps1
  tests/Integration/DSC_SqlLogin.Integration.Tests.ps1
  tests/Integration/DSC_SqlPermission.Integration.Tests.ps1
  tests/Integration/DSC_SqlProtocol.Integration.Tests.ps1
  tests/Integration/DSC_SqlProtocolTcpIp.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS.Integration.Tests.ps1
  tests/Integration/DSC_SqlRSSetup.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS_Default.Integration.Tests.ps1
  tests/Integration/DSC_SqlReplication.Integration.Tests.ps1
  tests/Integration/DSC_SqlRole.Integration.Tests.ps1
  tests/Integration/DSC_SqlScript.Integration.Tests.ps1
  tests/Integration/DSC_SqlScriptQuery.Integration.Tests.ps1
  tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1
  tests/Integration/DSC_SqlServiceAccount.Integration.Tests.ps1
  tests/Integration/DSC_SqlSetup.Integration.Tests.ps1
  tests/Integration/DSC_SqlTraceFlag.Integration.Tests.ps1
  tests/Integration/DSC_SqlWindowsFirewall.Integration.Tests.ps1
Labels: needs review

#1886 SqlServerDsc: Fix Stale exempt label
  .github/workflows/stale.yml
  CHANGELOG.md
Labels: needs review

#1887 SqlServerDsc: Some maintenance resolving issues
  CHANGELOG.md
  azure-pipelines.yml
  source/Public/Import-SqlDscPreferredModule.ps1
  tests/Integration/DSC_SqlRS.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS.config.ps1
  tests/Integration/DSC_SqlRS_Default.Integration.Tests.ps1
  tests/Integration/DSC_SqlRS_Default.config.ps1
Labels: needs review

#1890 `Restart-SqlService`: Correctly evaluate timeout value
  CHANGELOG.md
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
Labels: needs review
