Repository dsccommunity/SqlServerDsc, pull requests merged in 2023-04, with the labels that each got.

#1892 SqlSecureConnection: Added new parameter `ServerName`
  CHANGELOG.md
  source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.psm1
  source/DSCResources/DSC_SqlSecureConnection/DSC_SqlSecureConnection.schema.mof
  source/Examples/Resources/SqlSecureConnection/1-ForceSecureConnection.ps1
  tests/Integration/DSC_SqlSecureConnection.Integration.Tests.ps1
  tests/Integration/DSC_SqlSecureConnection.config.ps1
  tests/Unit/DSC_SqlSecureConnection.Tests.ps1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: needs review

#1898 `Get-SqlDscPreferredModule`: New command
  CHANGELOG.md
  source/Public/Get-SqlDscPreferredModule.ps1
  source/Public/Import-SqlDscPreferredModule.ps1
  source/en-US/SqlServerDsc.strings.psd1
  tests/Unit/Public/Get-SqlDscPreferredModule.Tests.ps1
  tests/Unit/Public/Import-SqlDscPreferredModule.Tests.ps1
Labels: needs review

#1900 SqlSetup: Add parameter ServerName
  CHANGELOG.md
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.schema.mof
  tests/Unit/DSC_SqlSetup.Tests.ps1
Labels: needs review

#1905 `Get-SqlDscPreferredModule`: Using command `Get-PSModulePath`
  CHANGELOG.md
  source/Public/Get-SqlDscPreferredModule.ps1
  tests/Unit/Public/Get-SqlDscPreferredModule.Tests.ps1
Labels: ready for merge

#1906 SqlServerDsc.Common: Removed the function `Invoke-Query`
  CHANGELOG.md
  source/DSCResources/DSC_SqlAGDatabase/DSC_SqlAGDatabase.psm1
  source/DSCResources/DSC_SqlDatabaseUser/DSC_SqlDatabaseUser.psm1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psd1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  source/Private/ConvertTo-RedactedText.ps1
  source/Public/Add-SqlDscTraceFlag.ps1
  source/Public/Disable-SqlDscAudit.ps1
  source/Public/Disconnect-SqlDscDatabaseEngine.ps1
  source/Public/Enable-SqlDscAudit.ps1
  source/Public/Invoke-SqlDscQuery.ps1
  source/Public/New-SqlDscAudit.ps1
  source/Public/Remove-SqlDscAudit.ps1
  source/Public/Remove-SqlDscTraceFlag.ps1
  source/Public/Set-SqlDscAudit.ps1
  source/Public/Set-SqlDscDatabasePermission.ps1
  source/Public/Set-SqlDscServerPermission.ps1
  source/Public/Set-SqlDscStartupParameter.ps1
  source/Public/Set-SqlDscTraceFlag.ps1
  source/en-US/SqlServerDsc.strings.psd1
  tests/Unit/DSC_SqlAGDatabase.Tests.ps1
  tests/Unit/DSC_SqlDatabaseUser.Tests.ps1
  tests/Unit/Private/ConvertTo-RedactedText.Tests.ps1
  tests/Unit/Public/Disconnect-SqlDscDatabaseEngine.Tests.ps1
  tests/Unit/Public/Invoke-SqlDscQuery.Tests.ps1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: ready for merge

#1911 SqlSetup: Add better validation of features
  CHANGELOG.md
  source/DSCResources/DSC_SqlSetup/DSC_SqlSetup.psm1
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Private/Assert-Feature.ps1
  source/Private/Assert-SetupActionProperties.ps1
  source/Private/Get-FileVersionInformation.ps1
  source/Public/Test-SqlDscIsSupportedFeature.ps1
  source/en-US/SqlServerDsc.strings.psd1
  tests/Unit/DSC_SqlSetup.Tests.ps1
  tests/Unit/Private/Assert-Feature.Tests.ps1
  tests/Unit/Private/Assert-SetupActionProperties.Tests.ps1
  tests/Unit/Private/Get-FileVersionInformation.Tests.ps1
  tests/Unit/Public/Test-SqlDscIsSupportedFeature.Tests.ps1
Labels: needs review

#1914 `Invoke-SetupAction`: Expand environment variables
  CHANGELOG.md
  source/Private/Invoke-SetupAction.ps1
Labels: needs review

#1904 SqlServerDsc: Using dbatools as a preferred module
  CHANGELOG.md
  azure-pipelines.yml
  source/Public/Get-SqlDscPreferredModule.ps1
  source/Public/Import-SqlDscPreferredModule.ps1
  source/WikiSource/Home.md
  tests/Integration/DSC_SqlSetup.Integration.Tests.ps1
  tests/Integration/DSC_SqlSetup.config.ps1
Labels: needs review

#1916 Connect-SQL: Add Wait for Online SMO Status
  CHANGELOG.md
  source/Modules/SqlServerDsc.Common/SqlServerDsc.Common.psm1
  source/Modules/SqlServerDsc.Common/en-US/SqlServerDsc.Common.strings.psd1
  source/Modules/SqlServerDsc.Common/sv-SE/SqlServerDsc.Common.strings.psd1
  tests/Unit/SqlServerDsc.Common.Tests.ps1
Labels: waiting for code fix

#1922 SqlDatabaseMail: Update integration tests to verify multiple instances
  CHANGELOG.md
  source/DSCResources/DSC_SqlDatabaseMail/DSC_SqlDatabaseMail.psm1
  tests/Integration/DSC_SqlDatabaseMail.Integration.Tests.ps1
  tests/Integration/DSC_SqlDatabaseMail.config.ps1
Labels: needs review

#1921 `Import-SqlDscPreferredModule`: Better handle preferred module
  CHANGELOG.md
  azure-pipelines.yml
  source/Public/Get-SqlDscPreferredModule.ps1
  source/Public/Import-SqlDscPreferredModule.ps1
  source/en-US/SqlServerDsc.strings.psd1
  tests/Unit/Public/Get-SqlDscPreferredModule.Tests.ps1
  tests/Unit/Public/Import-SqlDscPreferredModule.Tests.ps1
Labels: ready for merge
